# <center> Case Study - Zomato

> Create a new database and inserting the 7 sheets of the excel file into the MYSQL database.

In [2]:
import pandas as pd
from sqlalchemy import create_engine, text

In [11]:
# ── Step 1: Read ALL sheets at once ──────────────────────────────

all_sheets = pd.read_excel(r"zomato-schema.xlsx", sheet_name = None)

print(f"Found {len(all_sheets)} sheets: {list(all_sheets.keys())}")

Found 7 sheets: ['users', 'restaurants', 'food', 'menu', 'orders', 'delivery_partner', 'order_details']

In [17]:
# ── Step 2: Create the database if it doesn't exist ──────────────

engine = create_engine('mysql+pymysql://root:zain@localhost')

with engine.connect() as conn:
    conn.execute(text("CREATE DATABASE IF NOT EXISTS zomato"))
    
print("Database ready!")
engine.dispose()

Database ready!

In [18]:
# ── Step 3: Connect to the new database ──────────────────────────

engine = create_engine('mysql+pymysql://root:zain@localhost/zomato')

In [ ]:
# ── Step 4: Loop through each sheet and import as a table ────────

for sheet_name, df in all_sheets.items():
    # Clean sheet name: replace spaces with underscore for SQL safety
    
    table_name = sheet_name.strip().replace(" ", "_").lower()
    
    df.to_sql(
        name = table_name,
        con = engine,
        if_exists = 'replace',
        index = False,
        chunksize = 1000
    )
    
    print(f"Imported sheet '{sheet_name}' ➡ table '{table_name}' ({len(df)} rows)")
    
engine.dispose()

print("\nAll sheets imported successfully!")

Imported sheet 'users' ➡ table 'users' (7 rows)
Imported sheet 'restaurants' ➡ table 'restaurants' (5 rows)
Imported sheet 'food' ➡ table 'food' (11 rows)
Imported sheet 'menu' ➡ table 'menu' (15 rows)
Imported sheet 'orders' ➡ table 'orders' (25 rows)
Imported sheet 'delivery_partner' ➡ table 'delivery_partner' (5 rows)
Imported sheet 'order_details' ➡ table 'order_details' (50 rows)
/nAll sheets imported successfully!

# Zomato Database Schema Design

```mermaid
erDiagram

    USERS {
        int user_id PK
        string name
        string email
        string password
    }

    RESTAURANTS {
        int r_id PK
        string r_name
        string cuisine
    }

    FOOD {
        int f_id PK
        string f_name
        string type
    }

    MENU {
        int menu_id PK
        int r_id FK
        int f_id FK
        float price
    }

    ORDERS {
        int order_id PK
        int user_id FK
        int r_id FK
        float amount
        date date
        int partner_id FK
        int delivery_time
        int delivery_rating
        int restaurant_rating
    }

    DELIVERY_PARTNER {
        int partner_id PK
        string partner_name
    }

    ORDER_DETAILS {
        int id PK
        int order_id FK
        int f_id FK
    }

    USERS ||--o{ ORDERS : places
    RESTAURANTS ||--o{ ORDERS : receives
    DELIVERY_PARTNER ||--o{ ORDERS : delivers

    RESTAURANTS ||--o{ MENU : has
    FOOD ||--o{ MENU : contains

    ORDERS ||--o{ ORDER_DETAILS : includes
    FOOD ||--o{ ORDER_DETAILS : ordered

<center><span style="font-size: 20px;"> <b>  How Tables Are Connected</center> </b> 

`users` → `orders` via `user_id` — one user can place many orders

`restaurants` → `orders` via `r_id` — one restaurant receives many orders

`delivery_partner` → `orders` via `partner_id` — one partner delivers many orders

`orders` → `order_details` via `order_id` — one order can have multiple food items

`food` → `order_details` via `f_id` — one food item can appear in many orders

`restaurants` → `menu` via `r_id` — one restaurant has many menu items

`food` → `menu` via `f_id` — one food item can be on many restaurant menus

---  
---  
---

> On today's lecture we are gonna solve 20 question related to this database that is.

# <center>Questions

<span style="font-size: 18px;"> <b>Question: Connect to the zomato database

In [ ]:
%load_ext sql
%sql mysql+pymysql://root:zain@localhost/zomato
%config Sqlmagic.autopandas = True
%config Sqlmagic.feedback = False

<span style="font-size: 18px;"> <b>Question: Count number of rows

In [27]:
%%sql

SELECT COUNT(*) FROM orders

 * mysql+pymysql://root:***@localhost/zomato
1 rows affected.

[(25,)]

In [28]:
%%sql

SELECT COUNT(*) FROM menu

 * mysql+pymysql://root:***@localhost/zomato
1 rows affected.

[(15,)]

<span style="font-size: 18px;"> <b>Question: Return n random records

In [35]:
%%sql

SELECT * FROM order_details 
ORDER BY rand()
LIMIT 5;

 * mysql+pymysql://root:***@localhost/zomato
5 rows affected.

[(42, 1023, 3), (40, 1022, 1), (38, 1021, 1), (28, 1016, 8), (45, 1024, 3)]

<span style="font-size: 18px;"> <b>Question: Find null values.

In [36]:
%%sql

SELECT * from orders
wHERE restaurant_rating IS NULL

 * mysql+pymysql://root:***@localhost/zomato
8 rows affected.

[(1003, 1, 3, 240, datetime.datetime(2022, 6, 15, 0, 0), 5, 29, 4, None),
 (1006, 2, 1, 950, datetime.datetime(2022, 6, 10, 0, 0), 2, 16, 5, None),
 (1009, 2, 4, 300, datetime.datetime(2022, 7, 17, 0, 0), 4, 41, 1, None),
 (1013, 3, 2, 230, datetime.datetime(2022, 5, 30, 0, 0), 4, 45, 3, None),
 (1015, 3, 2, 230, datetime.datetime(2022, 6, 22, 0, 0), 3, 21, 5, None),
 (1017, 4, 4, 300, datetime.datetime(2022, 5, 30, 0, 0), 1, 50, 1, None),
 (1021, 5, 1, 550, datetime.datetime(2022, 7, 1, 0, 0), 5, 22, 2, None),
 (1025, 5, 2, 645, datetime.datetime(2022, 7, 28, 0, 0), 2, 44, 4, None)]

<span style="font-size: 18px;"> <b>Question: Replace the NULL values with 0 (do not the run the query just write the code)

In [ ]:
%%sql

# UPDATE order SET restaurant_rating = 0
# WHERE restaurant_rating IS NULL

<span style="font-size: 18px;"> <b>Question: Find orders placed by each customers

In [38]:
%%sql

SELECT
    t1.name,
    t2.order_id
FROM users t1
RIGHT JOIN orders t2
ON t1.user_id = t2.user_id

 * mysql+pymysql://root:***@localhost/zomato
25 rows affected.

[('Nitish', 1001),
 ('Nitish', 1002),
 ('Nitish', 1003),
 ('Nitish', 1004),
 ('Nitish', 1005),
 ('Khushboo', 1006),
 ('Khushboo', 1007),
 ('Khushboo', 1008),
 ('Khushboo', 1009),
 ('Khushboo', 1010),
 ('Vartika', 1011),
 ('Vartika', 1012),
 ('Vartika', 1013),
 ('Vartika', 1014),
 ('Vartika', 1015),
 ('Ankit', 1016),
 ('Ankit', 1017),
 ('Ankit', 1018),
 ('Ankit', 1019),
 ('Ankit', 1020),
 ('Neha', 1021),
 ('Neha', 1022),
 ('Neha', 1023),
 ('Neha', 1024),
 ('Neha', 1025)]

<span style="font-size: 18px;"> <b>Question: Find number of orders placed by each customers

In [47]:
%%sql

SELECT
    t1.name,
    COUNT(*) AS total_orders
FROM users t1
INNER JOIN orders t2
ON t1.user_id = t2.user_id
GROUP BY t1.user_id, t1.name;

 * mysql+pymysql://root:***@localhost/zomato
5 rows affected.

[('Nitish', 5), ('Khushboo', 5), ('Vartika', 5), ('Ankit', 5), ('Neha', 5)]

<span style="font-size: 18px;"> <b>Question: Find restaurant with most number of menu items.

In [53]:
%%sql

SELECT
    t1.r_name,
    COUNT(*)            AS '#of_food_items'
FROM restaurants t1
INNER JOIN menu t2
ON t1.r_id = t2.r_id
GROUP BY t1.r_id, t1.r_name

 * mysql+pymysql://root:***@localhost/zomato
5 rows affected.

[('dominos', 3), ('kfc', 3), ('box8', 3), ('Dosa Plaza', 3), ('China Town', 3)]

<span style="font-size: 18px;"> <b>Question: Find number of votes and avg rating for all the restaurants.

In [ ]:
%%sql

SELECT 
    t2.r_id,
    t2.r_name,
    COUNT(t2.r_id)                          AS '#of_votes',
    ROUND(AVG(restaurant_rating), 2)        AS 'Average_rating'
FROM orders t1
INNER JOIN restaurants t2
ON t1.r_id = t2.r_id
WHERE restaurant_rating IS NOT NULL
GROUP BY t2.r_id, t2.r_name

 * mysql+pymysql://root:***@localhost/zomato
5 rows affected.

[(1, 'dominos', 3, 1.67),
 (2, 'kfc', 5, 2.2),
 (3, 'box8', 3, 4.67),
 (5, 'China Town', 3, 3.67),
 (4, 'Dosa Plaza', 3, 3.67)]

<span style="font-size: 18px;"> <b>Question: Find the food that is being sold at most number of restaurants.

In [101]:
%%sql

SELECT
    t1.f_id,
    t2.f_name               AS 'food_name',
    COUNT(t1.r_id)          AS 'num_restaurants'
FROM menu t1
INNER JOIN food t2
ON t1.f_id = t2.f_id
GROUP BY t1.f_id, t2.f_name
HAVING num_restaurants = (
    SELECT COUNT(r_id)
    FROM menu 
    GROUP BY f_id
    ORDER BY COUNT(r_id) DESC
    LIMIT 1
)
ORDER BY food_name;

 * mysql+pymysql://root:***@localhost/zomato
2 rows affected.

[(3, 'Choco Lava cake', 3), (6, 'Rice Meal', 3)]

<h3>Understanding HAVING with Subquery in SQL</h3>

<p>Of course — let me explain it in very simple terms.</p>

<h2>What this query is trying to do</h2>

<p>The goal is to find the food item that appears in the <strong>maximum number of restaurants</strong>.<br>
So first we count, for each food, how many restaurants sell it. Then we keep only the food(s) with the highest count.</p>

<hr>

<h2>Break the query into parts</h2>

<pre><code>SELECT
    f.f_name AS food_name,
    COUNT(m.r_id) AS num_restaurants
FROM food f
INNER JOIN menu m ON f.f_id = m.f_id
GROUP BY f.f_id, f.f_name
HAVING num_restaurants = (
    SELECT COUNT(r_id)
    FROM menu
    GROUP BY f_id
    ORDER BY COUNT(r_id) DESC
    LIMIT 1
)
ORDER BY food_name;</code></pre>

<h3>1) <code>FROM food f INNER JOIN menu m ON f.f_id = m.f_id</code></h3>

<p>This joins the food table with the menu table.<br>
Why? Because <code>menu</code> tells us which food is available in which restaurant.</p>

<p>So after join, each row becomes something like:</p>

<ul>
<li>Choco Lava Cake + restaurant 1</li>
<li>Choco Lava Cake + restaurant 2</li>
<li>Choco Lava Cake + restaurant 3</li>
</ul>

<hr>

<h3>2) <code>GROUP BY f.f_id, f.f_name</code></h3>

<p>This groups all rows of the same food together.</p>

<p>So all “Choco Lava Cake” rows go into one group, all “Rice Meal” rows go into another group, and so on.</p>

<hr>

<h3>3) <code>COUNT(m.r_id) AS num_restaurants</code></h3>

<p>This counts how many restaurant entries each food has.</p>

<p>If a food appears in 3 restaurants, the count becomes 3.</p>

<hr>

<h2>Now the hard part: <code>HAVING ...</code></h2>

<p><code>HAVING</code> is used after <code>GROUP BY</code>.<br>
It filters groups, not individual rows.</p>

<p>So this part:</p>

<pre><code>HAVING num_restaurants = (
    ...
)</code></pre>

<p>means:</p>

<blockquote>
Keep only those foods whose restaurant count is equal to the biggest restaurant count.
</blockquote>

<hr>

<h2>What is inside the brackets?</h2>

<pre><code>(
    SELECT COUNT(r_id)
    FROM menu
    GROUP BY f_id
    ORDER BY COUNT(r_id) DESC
    LIMIT 1
)</code></pre>

<p>This part is just finding the <strong>highest count value</strong>.</p>

<h3>Step by step:</h3>

<p>1. <code>GROUP BY f_id</code><br>
Group menu rows by food id.</p>

<p>2. <code>COUNT(r_id)</code><br>
Count how many restaurants each food appears in.</p>

<p>3. <code>ORDER BY COUNT(r_id) DESC</code><br>
Sort from biggest count to smallest count.</p>

<p>4. <code>LIMIT 1</code><br>
Take only the top count.</p>

<p>So if the counts are:</p>

<ul>
<li>Rice Meal → 3</li>
<li>Choco Lava Cake → 3</li>
<li>Veg Pizza → 2</li>
<li>Masala Dosa → 1</li>
</ul>

<p>then the subquery returns:</p>

<pre><code>3</code></pre>

<p>So the outer query becomes:</p>

<blockquote>
Give me all foods where <code>num_restaurants = 3</code>.
</blockquote>

<hr>

<h2>Why this feels confusing</h2>

<p>Because the query is doing <strong>two jobs</strong>:</p>

<ul>
<li>Outer query: count restaurants for each food</li>
<li>Inner query: find the maximum count value</li>
</ul>

<p>Then <code>HAVING</code> compares both.</p>

<hr>

---  
---  
---

<span style="font-size: 18px;"> <b>Question: Find the restaurant with max revenue in a given month

In [112]:
%%sql

-- We are May, June, July data.
-- So we are gonna find max revenue in the `May` month

SELECT 
    MONTH(date),
    MONTHNAME(date),
    DAY(date),
    date 
FROM orders 
LIMIT 5;

 * mysql+pymysql://root:***@localhost/zomato
5 rows affected.

[(5, 'May', 10, datetime.datetime(2022, 5, 10, 0, 0)),
 (5, 'May', 26, datetime.datetime(2022, 5, 26, 0, 0)),
 (6, 'June', 15, datetime.datetime(2022, 6, 15, 0, 0)),
 (6, 'June', 29, datetime.datetime(2022, 6, 29, 0, 0)),
 (7, 'July', 10, datetime.datetime(2022, 7, 10, 0, 0))]

In [121]:
%%sql

SELECT
    t1.r_id,
    t2.r_name,
    SUM(t1.amount)          AS 'revenue'
FROM orders t1
INNER JOIN restaurants t2
ON t1.r_id = t2.r_id
WHERE MONTHNAME(date) = 'May'
GROUP BY t1.r_id, t2.r_name
ORDER BY revenue DESC;

 * mysql+pymysql://root:***@localhost/zomato
3 rows affected.

[(1, 'dominos', Decimal('1000')),
 (4, 'Dosa Plaza', Decimal('780')),
 (2, 'kfc', Decimal('645'))]

<span style="font-size: 18px;"> <b>Question: Find revenue per month for each restaurant

In [129]:
%%sql

SELECT
    t2.r_id,
    t2.r_name,
    MONTHNAME(date)         AS 'Month_NAME',
    SUM(t1.amount)          AS 'revenue'
FROM orders t1
INNER JOIN restaurants t2
ON t1.r_id = t2.r_id
GROUP BY t1.r_id, MONTHNAME(t1.date), t2.r_name
ORDER BY r_id;

 * mysql+pymysql://root:***@localhost/zomato
13 rows affected.

[(1, 'dominos', 'May', Decimal('1000')),
 (1, 'dominos', 'June', Decimal('950')),
 (1, 'dominos', 'July', Decimal('1100')),
 (2, 'kfc', 'May', Decimal('645')),
 (2, 'kfc', 'June', Decimal('990')),
 (2, 'kfc', 'July', Decimal('1935')),
 (3, 'box8', 'June', Decimal('480')),
 (3, 'box8', 'July', Decimal('460')),
 (4, 'Dosa Plaza', 'July', Decimal('300')),
 (4, 'Dosa Plaza', 'May', Decimal('780')),
 (4, 'Dosa Plaza', 'June', Decimal('400')),
 (5, 'China Town', 'July', Decimal('1050')),
 (5, 'China Town', 'June', Decimal('400'))]

<span style="font-size: 18px;"> <b>Question: Find restaurants sales > X

In [133]:
%%sql

SELECT
    t1.r_id,
    t2.r_name,
    SUM(t1.amount)          AS 'revenue'
FROM orders t1
INNER JOIN restaurants t2
ON t1.r_id = t2.r_id
GROUP BY t1.r_id, t2.r_name
HAVING revenue > 1000

 * mysql+pymysql://root:***@localhost/zomato
4 rows affected.

[(1, 'dominos', Decimal('3050')),
 (2, 'kfc', Decimal('3570')),
 (4, 'Dosa Plaza', Decimal('1480')),
 (5, 'China Town', Decimal('1450'))]

<span style="font-size: 18px;"> <b>Question: Find users who have never ordered

In [137]:
%%sql

SELECT *
FROM users
WHERE user_id NOT IN (
    SELECT DISTINCT(user_id)
    FROM orders
)

 * mysql+pymysql://root:***@localhost/zomato
2 rows affected.

[(6, 'Anupama', 'anupama@gmail.com', '46rdw2'),
 (7, 'Rishabh', 'rishabh@gmail.com', '4sw123')]

In [139]:
%%sql 

-- using left join now

SELECT *
FROM users t1
LEFT JOIN orders t2
ON t1.user_id = t2.user_id
WHERE order_id IS NULL

 * mysql+pymysql://root:***@localhost/zomato
2 rows affected.

[(6, 'Anupama', 'anupama@gmail.com', '46rdw2', None, None, None, None, None, None, None, None, None),
 (7, 'Rishabh', 'rishabh@gmail.com', '4sw123', None, None, None, None, None, None, None, None, None)]

In [144]:
%%sql 

-- using set operation EXCEPT

SELECT user_id, name
FROM users 
EXCEPT
SELECT t1.user_id, t2.name
FROM orders t1
INNER JOIN users t2
ON t1.user_id = t2.user_id

 * mysql+pymysql://root:***@localhost/zomato
2 rows affected.

[(6, 'Anupama'), (7, 'Rishabh')]

<span style="font-size: 18px;"> <b>`Question`: Show Order details of a particular customer in a given range

In [159]:
%%sql

SELECT
    t1.user_id,
    t1.order_id,
    DATE(t1.date),
    t3.f_name
FROM orders t1
JOIN order_details t2
ON t1.order_id = t2.order_id
JOIN food t3
ON t2.f_id = t3.f_id
WHERE t1.date BETWEEN '2022-05-10 00:00:00' AND '2022-06-30 00:00:00' AND user_id = 1
ORDER BY order_id;

 * mysql+pymysql://root:***@localhost/zomato
8 rows affected.

[(1, 1001, datetime.date(2022, 5, 10), 'Non-veg Pizza'),
 (1, 1001, datetime.date(2022, 5, 10), 'Choco Lava cake'),
 (1, 1002, datetime.date(2022, 5, 26), 'Choco Lava cake'),
 (1, 1002, datetime.date(2022, 5, 26), 'Chicken Wings'),
 (1, 1003, datetime.date(2022, 6, 15), 'Choco Lava cake'),
 (1, 1003, datetime.date(2022, 6, 15), 'Rice Meal'),
 (1, 1004, datetime.date(2022, 6, 29), 'Choco Lava cake'),
 (1, 1004, datetime.date(2022, 6, 29), 'Rice Meal')]

<span style="font-size: 18px;"> <b>`Question`: Find the customer favorite food

In [191]:
%%sql

-- this query is incomplete as it gives all the food items order by users but we only want the most ordered food for that we have to use `RANK` (see below).

SELECT
    t1.user_id,
    t1.name,
    t4.f_name,
    COUNT(*)        AS order_count
FROM users t1
JOIN orders t2
ON t1.user_id = t2.user_id
JOIN order_details t3
ON t2.order_id = t3.order_id
JOIN food t4
ON t3.f_id = t4.f_id
GROUP BY t1.user_id, t4.f_id, t1.name, t4.f_name
ORDER BY order_count DESC;

 * mysql+pymysql://root:***@localhost/zomato
25 rows affected.

[(5, 'Neha', 'Choco Lava cake', 5),
 (1, 'Nitish', 'Choco Lava cake', 5),
 (2, 'Khushboo', 'Choco Lava cake', 3),
 (5, 'Neha', 'Chicken Wings', 3),
 (3, 'Vartika', 'Chicken Wings', 3),
 (5, 'Neha', 'Chicken Popcorn', 3),
 (4, 'Ankit', 'Schezwan Noodles', 3),
 (4, 'Ankit', 'Veg Manchurian', 3),
 (5, 'Neha', 'Non-veg Pizza', 2),
 (2, 'Khushboo', 'Rice Meal', 2),
 (1, 'Nitish', 'Rice Meal', 2),
 (4, 'Ankit', 'Masala Dosa', 2),
 (4, 'Ankit', 'Rava Idli', 2),
 (3, 'Vartika', 'Non-veg Pizza', 1),
 (2, 'Khushboo', 'Non-veg Pizza', 1),
 (1, 'Nitish', 'Non-veg Pizza', 1),
 (2, 'Khushboo', 'Veg Pizza', 1),
 (2, 'Khushboo', 'Chicken Wings', 1),
 (1, 'Nitish', 'Chicken Wings', 1),
 (1, 'Nitish', 'Roti meal', 1),
 (3, 'Vartika', 'Masala Dosa', 1),
 (2, 'Khushboo', 'Masala Dosa', 1),
 (2, 'Khushboo', 'Rava Idli', 1),
 (2, 'Khushboo', 'Schezwan Noodles', 1),
 (2, 'Khushboo', 'Veg Manchurian', 1)]

In [ ]:
%%sql

SELECT
    user_id,
    name,
    f_name          AS favourite_food,
    order_count
FROM (
        SELECT 
            t1.user_id,
            t1.name,
            t4.f_name,
            COUNT(*)   AS order_count,
            RANK() OVER (PARTITION BY t1.user_id 
                         ORDER BY COUNT(*) DESC) AS rnk
        FROM users t1
        JOIN orders t2 ON t1.user_id = t2.user_id
        JOIN order_details t3 ON t2.order_id = t3.order_id
        JOIN food t4 ON t3.f_id = t4.f_id
        GROUP BY t1.user_id, t1.name, t4.f_id, t4.f_name
) ranked_foods
WHERE rnk = 1
ORDER BY user_id;

 * mysql+pymysql://root:***@localhost/zomato
6 rows affected.

[(1, 'Nitish', 'Choco Lava cake', 5),
 (2, 'Khushboo', 'Choco Lava cake', 3),
 (3, 'Vartika', 'Chicken Wings', 3),
 (4, 'Ankit', 'Schezwan Noodles', 3),
 (4, 'Ankit', 'Veg Manchurian', 3),
 (5, 'Neha', 'Choco Lava cake', 5)]

<span style="font-size: 18px;"> <b>`Question`: Find most costly restaurants(AVG price/ dish)

In [202]:
%%sql

SELECT
    t1.r_id,
    t2.r_name,
    ROUND(SUM(price) / COUNT(*), 2)       AS 'avg_price_dish'
FROM menu t1
JOIN restaurants t2 ON t1.r_id = t2.r_id
GROUP BY t1.r_id, t2.r_name
ORDER BY avg_price_dish DESC;

 * mysql+pymysql://root:***@localhost/zomato
5 rows affected.

[(1, 'dominos', Decimal('316.67')),
 (5, 'China Town', Decimal('216.67')),
 (2, 'kfc', Decimal('215.00')),
 (4, 'Dosa Plaza', Decimal('176.67')),
 (3, 'box8', Decimal('126.67'))]

<span style="font-size: 18px;"> <b>`Question`: Find delivery partner compensation using the formula (no. of delivery * 100 + 1000 * avg_rating)

In [230]:
%%sql

SELECT 
    t2.partner_id,
    t2.partner_name,
    COUNT(*)                           AS 'count_of_delivery',
    AVG(t1.delivery_rating)  AS 'avg_rating',
    ROUND((COUNT(*) * 100) + (1000 * AVG(t1.delivery_rating)),2)        AS 'compensation'
    
FROM orders t1
JOIN delivery_partner t2 ON t1.partner_id = t2.partner_id
GROUP BY t1.partner_id, t2.partner_name
ORDER BY partner_id;

 * mysql+pymysql://root:***@localhost/zomato
5 rows affected.

[(1, 'Suresh', 7, Decimal('2.8571'), Decimal('3557.14')),
 (2, 'Amit', 6, Decimal('3.0000'), Decimal('3600.00')),
 (3, 'Lokesh', 4, Decimal('4.0000'), Decimal('4400.00')),
 (4, 'Kartik', 4, Decimal('3.0000'), Decimal('3400.00')),
 (5, 'Gyandeep', 4, Decimal('3.5000'), Decimal('3900.00'))]

<span style="font-size: 18px;"> <b>`Question`: Find correlation between delivery_time and total rating

In [ ]:
%%sql

-- As mysql does have a corr function, we have 2 option: 1st calculate manually or the 2nd: use pandas corr

SELECT
    (AVG(delivery_time * delivery_rating) - AVG(delivery_time) * AVG(delivery_rating)) / 
    (SQRT(AVG(delivery_time * delivery_time) - AVG(delivery_time) * AVG(delivery_time)) * SQRT(AVG(delivery_rating * delivery_rating) - AVG(delivery_rating) * AVG(delivery_rating))) 
    AS correlation_coefficient
FROM orders

 * mysql+pymysql://root:***@localhost/zomato
1 rows affected.

[(-0.754438482192642,)]

In [237]:
df = pd.read_sql("""
SELECT
    delivery_time,
    delivery_rating
FROM orders
""", engine)

df.corr()

                 delivery_time  delivery_rating
delivery_time         1.000000        -0.754438
delivery_rating      -0.754438         1.000000

<span style="font-size: 18px;"> <b>`Question`: Find correlation between number of orders and avg price for all restaurants

In [ ]:
df = pd.read_sql("""
SELECT
    COUNT(*) AS num_orders,
    AVG(amount) AS avg_price
FROM orders
GROUP BY r_id
""", engine)

df.corr()

            num_orders  avg_price
num_orders    1.000000   0.121969
avg_price     0.121969   1.000000

<span style="font-size: 18px;"> <b>`Question`: Find all the restaurants, those only sell veg items

In [265]:
%%sql

SELECT
    t3.r_id,
    t3.r_name
FROM menu t1
JOIN food t2 ON t1.f_id = t2.f_id
JOIN restaurants t3 ON t1.r_id = t3.r_id
GROUP BY t3.r_id, t3.r_name
HAVING SUM(t2.type = 'Non-veg') = 0;

 * mysql+pymysql://root:***@localhost/zomato
3 rows affected.

[(3, 'box8'), (5, 'China Town'), (4, 'Dosa Plaza')]

<span style="font-size: 18px;"> <b>`Question`: Find min and max order value for all the customers

In [274]:
%%sql

SELECT 
    t1.user_id,
    t2.name,
    MIN(t1.amount),
    MAX(t1.amount),
    AVG(amount)
FROM orders t1
JOIN users t2 ON t1.user_id = t2.user_id
GROUP BY t1.user_id, t2.name

 * mysql+pymysql://root:***@localhost/zomato
5 rows affected.

[(1, 'Nitish', 220, 550, Decimal('333.0000')),
 (2, 'Khushboo', 240, 950, Decimal('534.0000')),
 (3, 'Vartika', 180, 450, Decimal('264.0000')),
 (4, 'Ankit', 300, 400, Decimal('360.0000')),
 (5, 'Neha', 550, 645, Decimal('607.0000'))]